const defaultValues: any = {
  patient_id: "0",
  age: 1,
  chemo_exposure: 0,
  fraction_genome_altered: 0,
  gene_panel: 0,
  mCRC_type: 0,
  metastasectomy: 0,
  metastases_site_first_bone: 0,
  metastases_site_first_brain: 0,
  metastases_site_first_gynecological: 0,
  metastases_site_first_liver: 0,
  metastases_site_first_ln: 0,
  metastases_site_first_lung: 0,
  metastases_site_first_pelvis: 0,
  metastases_site_first_peritoneum_omentum_abdomen: 0,
  metastatic_biopsy_site: 0,
  msi_score: 0,
  msi_status: 0,
  mutation_count: 0,
  overall_survival_months: 0,
  living_status: 0,
  other_metastasis_sites: 0,
  patient_tumor_grade: 0,
  primary_tumor_site: 0,
  primary_tumor_location: 0,
  sample_type: 0,
  sex: 0,
  specimen_type: 0,
  stage_at_diagnostic: 0,
  time_from_met_dx_to_sequencing: 0,
  time_to_81_months: 0,
};

export default defaultValues;
