const dataMap: any = {
  patient_id: "Patient id",
  age: "Age",
  chemo_exposure: "Chemo exposure",
  fraction_genome_altered: "Fraction genome altered",
  gene_panel: "Gene panel",
  mCRC_type: "mCRC type",
  metastasectomy: "Metastasectomy",
  metastases_site_first_bone: "Metastases site first bone",
  metastases_site_first_brain: "Metastases site first brain",
  metastases_site_first_gynecological: "Metastases site first gynecological",
  metastases_site_first_liver: "Metastases site first liver",
  metastases_site_first_ln: "Metastases site first ln",
  metastases_site_first_lung: "Metastases site first lung",
  metastases_site_first_pelvis: "Metastases site first pelvis",
  metastases_site_first_peritoneum_omentum_abdomen:
    "Metastases site first peritoneum omentum abdomen",
  metastatic_biopsy_site: "Metastatic biopsy site",
  msi_score: "MSI score",
  msi_status: "MSI status",
  mutation_count: "Mutation count",
  overall_survival_months: "Overall survival months",
  living_status: "Living status",
  other_metastasis_sites: "Other metastasis sites",
  patient_tumor_grade: "Patient tumor grade",
  primary_tumor_site: "Primary tumor site",
  primary_tumor_location: "Primary tumor location",
  sample_type: "Sample type",
  sex: "Sex",
  specimen_type: "Specimen type",
  stage_at_diagnostic: "Stage at diagnostic",
  time_from_met_dx_to_sequencing: "Time from met dx to sequencing",
  time_to_81_months: "Time to 81 months",
};

export default dataMap;
